INSERT INTO public.books (book_id, author, genre, page_count, publishing_year, title) values (1, 'Sherlocke Baake', 'Adventure|Comedy|Romance', 208, 1951, 'Tom Jones');
INSERT INTO public.books (book_id, author, genre, page_count, publishing_year, title) values (2, 'Breena Brogini', 'Action|Adventure|Drama', 528, 1932, 'Into the Wild');
INSERT INTO public.books (book_id, author, genre, page_count, publishing_year, title) values (3, 'Rowan Slide', 'Adventure|Animation|Children', 769, 1956, 'The Land Before Time X: The Great Longneck Migration');
INSERT INTO public.books (book_id, author, genre, page_count, publishing_year, title) values (4, 'Hallie Yuryev', 'Adventure|Comedy|Fantasy|Sci-Fi', 363, 1935, 'Time Bandits');
INSERT INTO public.books (book_id, author, genre, page_count, publishing_year, title) values (5, 'Geoff Brouncker', 'Comedy|Drama|Romance', 406, 2001, 'Irony of Fate, or Enjoy Your Bath! (Ironiya sudby, ili S legkim parom!)');
INSERT INTO public.books (book_id, author, genre, page_count, publishing_year, title) values (6, 'Donnajean Ellif', 'Documentary', 739, 1989, 'Iron Maiden: Flight 666');
INSERT INTO public.books (book_id, author, genre, page_count, publishing_year, title) values (7, 'Randy Probey', 'Horror|Sci-Fi|Thriller', 819, 1887, 'Cabin Fever: Patient Zero');
INSERT INTO public.books (book_id, author, genre, page_count, publishing_year, title) values (8, 'Carlotta Dosdill', 'Comedy|Drama', 558, 1971, 'Buddy');
INSERT INTO public.books (book_id, author, genre, page_count, publishing_year, title) values (9, 'Corrianne Ducastel', 'Documentary', 185, 1858, 'No One Dies in Lily Dale');
INSERT INTO public.books (book_id, author, genre, page_count, publishing_year, title) values (10, 'Elie Meddows', 'Adventure|Children|Fantasy', 202, 1924, 'Magic in the Water');
